# Generated by Django 4.0.3 on 2022-03-23 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condominium',
                'verbose_name_plural': 'Condominiums',
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='** No configuraro **', max_length=50)),
                ('is_multiple', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ProfileType',
                'verbose_name_plural': 'ProfileTypes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(default='+## ### ## ## ##', max_length=20)),
                ('is_base', models.BooleanField(blank=True, default=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('terms_confirmed', models.BooleanField(default=False)),
                ('condominiums', models.ManyToManyField(to='core.condominium')),
                ('last_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_work', to='core.condominium')),
                ('profiletype', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profiletype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
