# Generated by Django 4.0.3 on 2022-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagebank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='condominiums',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_work',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profiletype',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Condominium',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileType',
        ),
    ]
