# Generated by Django 4.0.3 on 2022-03-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagecategory_imagebank_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebank',
            name='description',
            field=models.CharField(blank=True, default='Coloque aqui una breve descripción de la imágen', max_length=120),
        ),
        migrations.AlterField(
            model_name='imagebank',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
