# Generated by Django 4.0.3 on 2022-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagebank_description_alter_imagebank_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebank',
            name='description',
            field=models.TextField(blank=True, default='Coloque aqui una breve descripción de la imágen', max_length=120),
        ),
    ]
