# Generated by Django 4.0.3 on 2022-03-24 08:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_imagebank_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebank',
            name='description',
            field=models.TextField(blank=True, default='Coloque aqui una breve descripción de la imagen', max_length=120),
        ),
        migrations.AlterField(
            model_name='imagebank',
            name='image',
            field=models.ImageField(default=None, upload_to=core.models.user_directory_path, verbose_name='Imagen'),
        ),
    ]
