# Generated by Django 4.0.3 on 2022-03-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_imagebank_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebank',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
